owner: abstractionfactory
repo: monitoring

sites:
  - name: Mail Health
    url: $MONITORING_URL
    headers:
    - "Authorization: $MONITORING_AUTHORIZATION"
  - name: Mail Certificate
    url: $MONITORING_CERT_URL
    headers:
    - "Authorization: $MONITORING_AUTHORIZATION"
  - name: Mail SSH
    url: $MONITORING_MAIL_SSH
    port: $MONITORING_MAIL_SSH_PORT
    check: "tcp-ping"
    
  - name: Storage SSH
    url: $MONITORING_STORAGE_SSH
    port: $MONITORING_STORAGE_SSH_PORT
    check: "tcp-ping"
