owner: abstractionfactory
repo: monitoring

sites:
  - name: Mail Health
    url: $MONITORING_URL
    headers:
    - "Authorization: $MONITORING_AUTHORIZATION"
  - name: Mail Certificate
    url: $MONITORING_CERT_URL
    headers:
    - "Authorization: $MONITORING_AUTHORIZATION"
  - name: Mail SSH
    url: $MONITORING_MAIL_SSH
    port: $MONITORING_MAIL_SSH_PORT
    check: "tcp-ping"
    
  - name: Storage SSH
    url: $MONITORING_STORAGE_SSH
    port: $MONITORING_MAIL_SSH_PORT
    check: "tcp-ping"

workflowSchedule:
  uptime: "0 * * * *"

status-website:
  baseUrl: /monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoring
  introTitle: ""
  introMessage: ""
  robotsText: "User-agent: * \n Disallow: /"
skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

commitMessages:
  commitAuthorName: "AbstractionFactory"
  commitAuthorEmail: "179820029+abstractionfactory@users.noreply.github.com"
